// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

/** @public */
export const LANGUAGES = [
	{ label: 'Bahasa Indonesia', locale: 'id' },
	{ label: 'Deutsch', locale: 'de' },
	{ label: 'English', locale: 'en' },
	{ label: 'Español', locale: 'es' },
	{ label: 'Français', locale: 'fr' },
	{ label: 'Italiano', locale: 'it' },
	{ label: 'Русский', locale: 'ru' },
	{ label: '日本語', locale: 'ja' },
] as const
